# Generated by Django 4.2.5 on 2023-09-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('non-binary', 'Non-Binary'), ('other', 'Other'), ('none', 'Prefer not to Answer')], max_length=20, null=True, verbose_name='Gender'),
        ),
    ]
