# Generated by Django 4.2.5 on 2023-09-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=30, unique=True, verbose_name='Order Number')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='Payment ID')),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('processing', 'Processing'), ('error', 'Error')], verbose_name='Payment Status')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='Payment Time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('oder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
