# Generated by Django 4.2.5 on 2023-10-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipping.shippingcontact', verbose_name='Shipping Contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipping.trackinginfo', verbose_name='Tracking Info'),
        ),
    ]
