# Generated by Django 4.2.5 on 2023-10-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_initial'),
        ('orders', '0004_remove_orderitem_oder_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shipping.trackinginfo', verbose_name='Tracking Info'),
        ),
    ]
