# Generated by Django 4.2.5 on 2023-10-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_tracking_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('awaiting_payment', 'Awaiting Payment'), ('partially_shipped', 'Partially Shipped'), ('returned', 'Returned'), ('refunded', 'Refunded')], null=True, verbose_name='Order Status'),
        ),
    ]
