# Generated by Django 4.2.5 on 2023-09-30 03:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='brands/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Category name')),
                ('code', models.CharField(default='', max_length=30, verbose_name='Category code')),
                ('desc', models.TextField(default='', verbose_name='Category description')),
                ('category_type', models.CharField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], verbose_name='Category type')),
                ('is_featured', models.BinaryField(default=False, verbose_name='Is featured')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('clicks_count', models.IntegerField(default=0, verbose_name='Total Clicks')),
                ('sold_count', models.IntegerField(default=0, verbose_name='Total Sold')),
                ('favorites_count', models.IntegerField(default=0, verbose_name='Total Favorite')),
                ('in_stock', models.IntegerField(default=0, verbose_name='In Stock')),
                ('discount', models.BooleanField(default=False, verbose_name='On Sale')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Rate (%)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('short_desc', models.TextField(max_length=500, verbose_name='Short Description')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Free Shipping')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Thumbnail')),
                ('is_new', models.BooleanField(default=False, verbose_name='Newly arrival')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Product Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Images')),
                ('image_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Image URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Hero Image')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
            },
        ),
    ]
